// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkdUt3KJxMCowD8aW8BhPlAoUBUueP7IU',
    appId: '1:321081180947:web:84188f99a2030ff21310e6',
    messagingSenderId: '321081180947',
    projectId: 'casa-do-sushi-d05f9',
    authDomain: 'casa-do-sushi-d05f9.firebaseapp.com',
    storageBucket: 'casa-do-sushi-d05f9.firebasestorage.app',
    measurementId: 'G-KELRYL64WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnVDnImURTwroZpIkB74iF5YYNAbM7A-s',
    appId: '1:321081180947:android:ed4c0aedfa2ac26d1310e6',
    messagingSenderId: '321081180947',
    projectId: 'casa-do-sushi-d05f9',
    storageBucket: 'casa-do-sushi-d05f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj5mmUmD_J9-AohRRI59BQ2QdMZL2816I',
    appId: '1:321081180947:ios:3237549c732ccffa1310e6',
    messagingSenderId: '321081180947',
    projectId: 'casa-do-sushi-d05f9',
    storageBucket: 'casa-do-sushi-d05f9.firebasestorage.app',
    iosBundleId: 'com.casadosushi.casadosushi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj5mmUmD_J9-AohRRI59BQ2QdMZL2816I',
    appId: '1:321081180947:ios:3237549c732ccffa1310e6',
    messagingSenderId: '321081180947',
    projectId: 'casa-do-sushi-d05f9',
    storageBucket: 'casa-do-sushi-d05f9.firebasestorage.app',
    iosBundleId: 'com.casadosushi.casadosushi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkdUt3KJxMCowD8aW8BhPlAoUBUueP7IU',
    appId: '1:321081180947:web:2badd0d0ef7b54511310e6',
    messagingSenderId: '321081180947',
    projectId: 'casa-do-sushi-d05f9',
    authDomain: 'casa-do-sushi-d05f9.firebaseapp.com',
    storageBucket: 'casa-do-sushi-d05f9.firebasestorage.app',
    measurementId: 'G-5CKHB5HTD0',
  );
}
